export const LOAD_QUESTIONS = 'LOAD_QUESTIONS';
export const CREATE_QUESTION = 'CREATE_QUESTION';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const RESTART_QUESTIONS = 'RESTART_QUESTIONS';
export const NEXT_QUESTION = 'NEXT_QUESTION';
